### PR TITLE
ZeldaLinkAaron optifine beds

### PR DESCRIPTION
**Pull request by ZeldaLinkAaron**
Made beds have a more 3D model with Optifine

### CODE REVIEW

**Comment by Sollace** [comment]
For situations like this, I think it would help if you included screenshots. Also you can have 3d beds without needing optifine.

**Comment by Sollace** [comment]
@ZeldaLinkAaron

**Comment by ZeldaLinkAaron** [comment]
image
image
Also, I've not seen anything anywhere about how to modify entity models without creating a mod or using optifine.

**Comment by ZeldaLinkAaron** [comment]
I also noticed a little broken texture on the rest of the beds, I'll fix this in my working branch later.

**Comment by Sollace** [comment]
Pretty sure beds are no longer entities in 1.13/1.14

**Comment by ZeldaLinkAaron** [comment]
image
I don't see them not being entities anymore and if they weren't entities, how would I be able to change their entity model?

**Comment by Sollace** [comment]
Hm. Thought they undid that for the flattening. The only reason they had to be tile entities before was due to the limitations of the old 16 meta values.
64196100-b1f37380-ce48-11e9-8711-030583c9afce

**Pull request merged**
