### PR TITLE
recipe button and survival gui

### PR DESCRIPTION
**Pull request by PCelestia**
I did remove the old effect icons, but I still have the old file if needed

### CODE REVIEW

**Comment by Sollace** [comment]
Can you give some screenshots of what it looks like in game?

**Comment by PCelestia** [comment]
image
image
I havent textured the recipe book yet, and in the second image, I am hovering over the recipe book button

**Comment by Sollace** [comment]
A few notes:
 1. I don't like that the recipe book looks too much like a regular book floating on the screen
 2. Can you remove the white border along the bottom and right in the recipe window, or otherwise try to hide it among the rest of the UI?
 3. The tabs have a much better colour than the body of the recipe book gui. Perhaps use that for all of it and make the unselected tabs a slightly darker shade?

**Comment by PCelestia** [comment]
I haven't addressed number 1 yet

**Comment by PCelestia** [comment]
oh and the book icon is the same as the current one from the pack

**Pull request merged**
